<%@ Page Title="Back&" Language="C#" MasterPageFile="~/Website/Main.Master" AutoEventWireup="true"%>
<%@ Register TagPrefix="My" TagName="MenuControl" Src="Menu.ascx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Main" runat="server">
        <My:MenuControl runat="server" ID="MenuControl1" MenuSelected=""/>

        <div class="rowcontent page404">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 text-justify">
                    <h1>Terms of Use</h1>
                    <p>THIS IS AN AGREEMENT BETWEEN YOU OR THE ENTITY THAT YOU REPRESENT AND MODUBIZ LTD. AND ITS AFFILIATES AND SUBSIDIARIES (Individually and collectively, "ModuBiz") GOVERNING YOUR USE OF MODUBIZ BACK-OFFICE SOFTWARE AS A SERVICE (SAAS) PLATFORM FOR APPS ("SERVICES"). If you do not agree to the Terms of Use ("Terms of Use" or "Terms"), do not use any of our Services. You can accept the Terms by checking a checkbox indicating your acceptance of the Terms or by actually using the Services.</p>
                    <h3>Services Provided by ModuBiz</h3>
                    <p>Subject to these Terms of Use ModuBiz hereby grants to you a limited, non-exclusive, personal, non-transferable, non- assignable and revocable license to access and use the Services solely for your own internal business purposes (the "License"). All rights not expressly granted to you herein are reserved by ModuBiz. You are authorized to access and use the Services and to otherwise freely use all tools, features, and capabilities of the Services in accordance with these Terms of Use. ModuBiz provides a platform and associated applications which, among others, contain online database management functionality, using innovative technology to CRUD, analyze, fix, report and manage data. Through ModuBiz web site (backand.com) (the "Site"), platform and applications available on it (the "Site Applications"), ModuBiz clients (the "Clients") can obtain a License for the use of ModuBiz Services, through which their team and users (website users or other users) (“Users” or “User”) can build and operate a data driven back-office application for a database. In order to have access to any of the Site Applications you will be required to register with ModuBiz and choose the Site Applications you wish to use. You may connect to the Services using any Internet browser supported by the Services. You are responsible for obtaining access to the Internet and the equipment required using the Services.</p>
                    <h3>Fees</h3>
                    <p>Some Services are provided free of charge and others are provided subject to payment of fees. Subscriptions to paid Services are available on monthly subscription plan. You may elect to change your account from free account to paying account, or change your payment method, according to ModuBiz offered plans, by electronic means available on the Site. We reserve the right to change from time to time the prices rendered for our Licenses and/or Services and to charge for use of Services that are currently available free of charge.</p>
                    <h3>General Practices Regarding Use and Storage</h3>
                    <p>Subject to the terms of your license you acknowledge and agree that ModuBiz, in its sole discretion, with or without notice, may establish or revise from time to time general practices and limits concerning your use of the Services, including without limitation, establishing the maximum amount of storage space you have on the Site at any time. ModuBiz also reserves the right to change, modify, suspend or discontinue any portion of the Site and/or the Services at any time and ModuBiz may also impose limits on certain features or restrict your access to parts or the entire Site without notice or liability. If you do not agree to any such updates or changes, your sole remedy shall be to discontinue the use of the Services. You agree that ModuBiz has no responsibility or liability for the deletion, corruption, or alteration of your data or failure to store any data, text (including but not limited to files, databases, directories and groups/workgroups) (collectively referred to as "Content") provided by you and maintained or transmitted by the Services.</p>      
                    <h3>Links</h3>
                    <p>ModuBiz may provide links to other sites or resources. Because ModuBiz has no control over such sites and resources, you acknowledge and agree that ModuBiz is not responsible for the availability or accuracy of such external sites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products, intellectual property notices or other materials on or available from such sites or resources. You further acknowledge and agree that ModuBiz shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site or resource.</p>
                    <h3>Personal Information, Privacy and Security</h3>
                    <p>Personal information you provide to ModuBiz through the Services is governed by ModuBiz Privacy Policy. Your election to use the Services indicates your acceptance of the terms of the ModuBiz Privacy Policy. ModuBiz utilizes some of the most advanced technology for Internet security available today. When you access certain non-public components of our Site using Firefox 2.0 or later or Microsoft Internet Explorer versions 6.0 or later, Secure Socket Layer (SSL) technology protects your data using both server authentication and data encryption. These technologies help ensure that your data is safe, secure and only available to the registered Users in your organization. ModuBiz will use all means available to it to ensure that your data will be completely inaccessible to your competitors. For security purposes, ModuBiz provides both a private password and login specifications for each of your Users. In addition, ModuBiz is hosted in a secure server environment that uses a firewall and other advanced technology to prevent interference or access from outside intruders. You are responsible for maintaining confidentiality of your username, password and other sensitive information. You are responsible for all activities that occur in your user account and you agree to inform us immediately of any unauthorized use of your user account by email to info@Modubiz.com. We are not responsible for any loss or damage to you or to any third party incurred as a result of any unauthorized access and/or use of your user account, or otherwise.</p>
                    <h3>Communications from ModuBiz</h3>
                    <p>Your consent during the registration process to receive updates and marketing materials of ModuBiz, means that you agree and authorize ModuBiz to make use of the information you provided ModuBiz during the registration process for the purpose of (i) improving ModuBiz services provided to you, (ii) sending you certain communications from ModuBiz, such as notifications of ModuBiz products and services which might interest you; ModuBiz newsletters and other advertising information; service announcements and administrative messages, by e-mail or by any other means of communication provided by you (Collectively referred to as "Communications from ModuBiz" or "Communications"). As part of our policy to provide you total privacy, we also provide you the option of opting out from receiving such Communications from us. You have the right to notify ModuBiz, at any time, of your refusal to receive such Communications from ModuBiz by contacting ModuBiz or by mail.</p>
                    <h3>User Sign up Obligations</h3>
                    <p>In consideration for your use of the Services, you agree to: (a) provide true, accurate, current and complete information about yourself in the required fields of the registration form(s) (the "Registration Data") and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or ModuBiz has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, ModuBiz may suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).</p>
                    <h3>Spamming and Illegal Activities</h3>
                    <p>You agree to not use the Services to: (a) upload or otherwise transmit any Content or domain name that is unlawful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable; (b) harm minors in any way; (c) impersonate any person or entity, including, but not limited to, any ModuBiz representative, or misrepresent your affiliation with any person or entity; (d) forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Services; (e) upload or otherwise transmit any Content that you do not have a right to transmit under any law or under contractual relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements); (f) upload or otherwise transmit any Content or domain name that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any person; (g) upload or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation, except in those areas of the Services that may be designated for such purpose; (h) upload or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (i) interfere with or disrupt the Services or servers or networks connected to the Services; (j) violate any applicable law or regulation (k) incite or provide instructional information about illegal activities.</p>
                    <h1></h1>
                    <h3>Restrictions on Use</h3>
                    <p>You agree not to copy, or create a derivative work of any portion of the Services, use of the Services, or access to the Services. Such restrictions do not apply to the Content you place on the Site. You agree not to access the Services by any means other than through the interface that is provided by ModuBiz for use in accessing the Services.</p>
                    <h3>Content Submitted to the Site.</h3>
                    <p>By submitting any Content to ModuBiz, you warrant that: (i) you are the owner of such Content, or have all the rights necessary to submit such Content to ModuBiz, and (ii) the use of such Content by ModuBiz and its members will not infringe or misappropriate the intellectual property rights of or otherwise violate the rights of any third party. ModuBiz will investigate notices of intellectual property infringement and take appropriate actions. If you believe that your work has been used or copied in a way that constitutes intellectual property infringement and such infringement is occurring on this Site or on sites linked to from this Site, please notify ModuBiz. You understand that all Content, whether publicly posted or privately transmitted, is the sole responsibility of the person from which such Content originated. This means that you, and not ModuBiz, are entirely responsible for all Content that you upload or otherwise transmit via the Services. ModuBiz does not control the Content uploaded or otherwise transmitted by you or other customers via the Services and, as such, does not guarantee the accuracy, integrity or quality of such Content. You are responsible for ensuring that you do not accidentally make any private content publicly available. Any content that you may receive from other Users of the Services, is provided to you AS IS for your information and personal use only and you agree not to use, copy, reproduce, distribute, transmit, broadcast, display, sell, license or otherwise exploit such content for any purpose, without the express written consent of the person who owns the rights to such content.</p>
                    <h3>Applications Created by a Developer.</h3>
                    <p>If you are a developer, using the Services as a platform for development of an application to which you own all proprietary rights, you acknowledge and agree that (i) the users of your application are solely your clients and not clients of ModuBiz, (ii) you will enter into an agreement with such clients to protect your proprietary rights in connection with such application, and (iii) ModuBiz is not responsible for your application, or for support to your clients, even if your application is used in connection with the Service.</p>
                    <h3>Intellectual Property and other Proprietary Rights.</h3>
                    <p>Modubiz retains ownership and all rights to all Modubiz logos, icons, trademarks, software, trade secrets, databases, reports, the Site Applications and the Site and all content therein. You acknowledge and agree that the Services, the Site and the Site Applications contain proprietary and confidential information that is protected by applicable intellectual property and other laws, and you agree not to display, use or disclose such information to any third party without ModuBiz's prior permission. In the course of using any of the Services, if you come across any content with copyright notice(s) or any copy protection feature(s), you agree not to remove such copyright notice(s) or disable such copy protection feature(s) as the case may be.</p>
                    <h3>Data Ownership.</h3>
                    <p>You grant ModuBiz the right to use Content submitted by you to the Site only to the extent that ModuBiz needs to use such Content to provide the Services. ModuBiz does not obtain any right, title or interest in your Content, except as specifically granted herein in order to provide Services to you. You acknowledge that ModuBiz will collect and use certain aggregate data as part of providing and analyzing the Services from time to time, all according to ModuBiz Privacy Policy.</p>
                    <h3>Registered Entities.</h3>
                    <p>If you are a Registered Entity and permit your affiliates, subsidiaries, employees, and/or any third party to access and/or use the Services and/or your Content, you shall be solely responsible for (i) their acts and/or omissions in connection with their access and/or use of the Services and (ii) ensuring that their access and/or use of the Services is in compliance with these Terms of Use, and any and all applicable local laws, rules and regulations. You agree to fully indemnify ModuBiz for any liability, fines, penalties, costs, claims and/or damages incurred by ModuBiz in connection with any claim related to the access and/or use of the Services and/or your Content by you, your affiliates, subsidiaries, employees or any third-party authorized by you. You agree to notify ModuBiz immediately upon discovery of any unauthorized access or use of the Services, or any password or account, or any known or suspected breach of security in connection with the Services.</p>
                    <h3>Modifications to the Services or Agreements.</h3>
                    <p>ModuBiz reserves the right at any time and from time to time to modify the Services (or any part thereof) with or without notice. You agree that ModuBiz shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Services, or for any resulting loss or destruction of any Content that you place on the Site. ModuBiz may periodically modify these Terms of Use. Your continued use of the Services after such modification shall constitute your acceptance of the Terms of Use with the new modifications. If you do not agree to any of such changes, you may terminate the Terms of Use and immediately cease all access and use of the Services. In all cases, you and all Users agree that termination of the Terms of Use and cessation of all access and use of the Services would be the exclusive remedy if you and such Users do not wish to comply with the Terms of Use provided by ModuBiz.</p>
                    <h3>Term, Suspension and Termination.</h3>
                    <p>This agreement commence on the date you accept it and continues until all Services granted in accordance with this agreement have expired or been terminated. You acknowledge and agree that ModuBiz in its sole discretion, may suspend or terminate your account and/or deny you access to, use of, or submission of Content for, all or part of the Services, without prior notice and for any reason, including if you engage in any conduct that ModuBiz believes: (i) violates any term or provision of the Terms of Use, (ii) violates the rights of ModuBiz or third parties, or (iii) is otherwise inappropriate for continued access and use of the Services. You agree that upon termination, ModuBiz may delete all files and information related to your account and may bar your access to your account and the Services. We will also terminate your user account on your request. Further, you agree that ModuBiz shall not be liable to you or any third party for any termination of your access to the Services.</p>
                    <h3>Disclaimer of Warranties.</h3>
                    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. EXCEPT AS EXPRESSLY PROVIDED OTHERWISE IN A WRITTEN AGREEMENT BETWEEN YOU AND MODUBIZ, THE SERVICES, THE SITE, THE SITE APPLICATIONS, THE LICENSES AND ANY MATERIALS INCLUDED THEREIN ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. MODUBIZ EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. MODUBIZ MAKES NO WARRANTY THAT (i) THE SERVICES WILL MEET YOUR REQUIREMENTS OR RESULT IN REVENUES OR PROFITS, (ii) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVERS THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, AND (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICES, THE SITE AND THE SITE APPLICATIONS WILL MEET YOUR EXPECTATIONS. UNLESS SUCH REPRESENTATIONS AND WARRANTIES ARE NOT LEGALLY EXCLUDABLE, MODUBIZ EXPRESSLY DISCLAIMS ANY REPRESENTATIONS OR WARRANTIES THAT YOUR USE OF THE SERVICE WILL SATISFY ANY STATUTORY OR REGULATORY OBLIGATIONS, OR WILL ASSIST WITH, GUARANTEE OR OTHERWISE ENSURE COMPLIANCE WITH ANY APPLICABLE LAWS OR REGULATIONS. YOU ARE SOLELY RESPONSIBLE FOR ENSURING THAT YOUR USE OF THE SERVICES, THE SITE AND THE SITE APPLICATIONS IS IN ACCORDANCE WITH ANY APPLICABLE LAW. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DOWNLOADED OR OBTAINED AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM MODUBIZ OR THROUGH OR FROM THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS OF USE.</p>
                    <h3>Limitation of Liability.</h3>
                    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT MODUBIZ SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF MODUBIZ HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICES, THE SITE OR THE SITE APPLICATIONS; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICES, THE SITE OR THE SITE APPLICATIONS; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICES; OR (v) ANY OTHER MATTER RELATING TO THE SERVICES. YOU ALSO AGREE THAT MODUBIZ WILL NOT BE LIABLE FOR ANY (i) INTERRUPTION OF BUSINESS, (ii) ACCESS DELAYS OR ACCESS INTERRUPTIONS TO THIS SITE (iii) DATA NON-DELIVERY, MIS-DELIVERY, CORRUPTION, DESTRUCTION OR OTHER MODIFICATION (iv) UNAUTHORIZED ACCESS TO DATA ENTERED IN, OR BREACH OF ANY SECURITY MECHANISMS UTILIZED IN, THE SERVICES, THE SITE, THE SITE APPLICATIONS OR IN ANY RESTRICTED FIELD THEREIN; OR (v) EVENTS BEYOND MODUBIZ REASONABLE CONTROL. IN NO EVENT SHALL MODUBIZ TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE, EXCEED THE AMOUNT PAID BY YOU, IF ANY, IN RESPECT TO THE SERVICES PROVIDED TO YOU BY MODUBIZ. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES IN CERTAIN CIRCUMSTANCES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
                    <h3>Indemnity.</h3>
                    <p>You agree to indemnify and hold ModuBiz and its directors, officers, agents and employees ("Indemnitees"), harmless, from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your Content; your use of the Services, the Site and the Site Applications; your connection to the Services, the Site or the Site Applications; your violation of the Terms of Use; or your violation of any proprietary or other rights of another. You further agree and acknowledge that the Indemnitees are not liable or responsible in any way for any errors, omissions or any other actions arising out of or related to your use of the Service, the Site or the Site Applications. You further agree to indemnify, defend and hold harmless the Indemnitees from and against any and all claims, damages, liabilities, costs, and expenses (including reasonable legal fees and expenses) arising out of, or related to, your use of the Services, the Site or the Site Applications, or the placement or transmission of any message, information, software or other materials through the Services by you or Users of your account or related to any violation of any term of the Terms of Use by you or Users of your account.</p>
                    <h3>General Information.</h3>
                    <p>i. You must be of legal age to enter into a binding agreement in order to accept these Terms of Use. ii. Notices to you may be made via e-mail, regular mail, overnight courier or facsimile at your contact addresses of record for the Services. iii. The Terms of Use constitute the entire agreement between you and ModuBiz and governs your use of the Services, the Site and the Site Applications, superseding any prior agreements, understandings, negotiations, and discussions, whether oral or written, between you and ModuBiz with respect to the subject matter herein. iv. By accessing this Site, you and ModuBiz agree that all matters relating to your access to, or use of, this Site shall be governed by and construed in accordance with the laws of the State of Israel, without giving effect to any principles of conflicts of law. You and ModuBiz irrevocably submit to the exclusive jurisdiction of the courts of Tel Aviv - Yafo, Israel. We reserve the right to change from time to time the laws and jurisdiction to which these Terms of Use shall be subject to, as shall be updated from time to time in these Terms of Use. v. The Terms of Use do not limit any rights that ModuBiz may have under trade secret, copyright, patent, trademark or other laws. The failure of ModuBiz to exercise or enforce any right or provision of the Terms of Use shall not constitute a waiver of such right or provision. If any provision of the Terms of Use is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms of Use remain in full force and effect. The section titles in the Terms of Use are for convenience only and have no legal or contractual effect.</p>
                    <br />
                    <p>If you have any questions or concerns regarding these Terms of Use please contacts us at: <a href="mailto:team@<%=Durados.Database.LongProductName %>.com">team@<%=Durados.Database.LongProductName %>.com</a></p>
                    <br/>
                    <br/>
                    <br/>
                    <div class="clearfix"></div>
                    <br/>
                    </div>
                </div>
                <p class="text-center"><a href="javascript:;" class="btn-yellow btn-yellow-short ">TRY FOR <strong>FREE</strong> >></a></p>
            </div>
        </div>
</asp:Content>