//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_Content_ContentType", "ContentType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Cms.Model.ContentType), "Content", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.Content))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_PageContent_Content", "Content", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Content), "PageContent", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.PageContent))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_Link_Page", "Page", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Cms.Model.Page), "Link", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.Link))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_LinkParameter_Link", "Link", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Link), "LinkParameter", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.LinkParameter))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_MenuItem_Link", "Link", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Link), "MenuItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.MenuItem))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_LinkParameter_Parameter", "Parameter", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Parameter), "LinkParameter", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.LinkParameter))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_Page_Master", "Master", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Master), "Page", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.Page))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_MenuItem_Menu", "Menu", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Menu), "MenuItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.MenuItem))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_MenuItem_MenuItem", "MenuItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Cms.Model.MenuItem), "MenuItem1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.MenuItem))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_PageContent_Page", "Page", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Page), "PageContent", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.PageContent))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_ContentParameter_Content", "Content", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Content), "ContentParameter", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.ContentParameter))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Cms.Model", "FK_ContentParameter_Parameter", "Parameter", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cms.Model.Parameter), "ContentParameter", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cms.Model.ContentParameter))]

// Original file name:
// Generation date: 09/05/2010 07:21:35
namespace Cms.Model
{
    
    /// <summary>
    /// There are no comments for CmsDB in the schema.
    /// </summary>
    public partial class CmsDB : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CmsDB object using the connection string found in the 'CmsDB' section of the application configuration file.
        /// </summary>
        public CmsDB() : 
                base("name=CmsDB", "CmsDB")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CmsDB object.
        /// </summary>
        public CmsDB(string connectionString) : 
                base(connectionString, "CmsDB")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CmsDB object.
        /// </summary>
        public CmsDB(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CmsDB")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Content> Content
        {
            get
            {
                if ((this._Content == null))
                {
                    this._Content = base.CreateQuery<Content>("[Content]");
                }
                return this._Content;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Content> _Content;
        /// <summary>
        /// There are no comments for ContentType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ContentType> ContentType
        {
            get
            {
                if ((this._ContentType == null))
                {
                    this._ContentType = base.CreateQuery<ContentType>("[ContentType]");
                }
                return this._ContentType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ContentType> _ContentType;
        /// <summary>
        /// There are no comments for Link in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Link> Link
        {
            get
            {
                if ((this._Link == null))
                {
                    this._Link = base.CreateQuery<Link>("[Link]");
                }
                return this._Link;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Link> _Link;
        /// <summary>
        /// There are no comments for LinkParameter in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LinkParameter> LinkParameter
        {
            get
            {
                if ((this._LinkParameter == null))
                {
                    this._LinkParameter = base.CreateQuery<LinkParameter>("[LinkParameter]");
                }
                return this._LinkParameter;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LinkParameter> _LinkParameter;
        /// <summary>
        /// There are no comments for Master in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Master> Master
        {
            get
            {
                if ((this._Master == null))
                {
                    this._Master = base.CreateQuery<Master>("[Master]");
                }
                return this._Master;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Master> _Master;
        /// <summary>
        /// There are no comments for Menu in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Menu> Menu
        {
            get
            {
                if ((this._Menu == null))
                {
                    this._Menu = base.CreateQuery<Menu>("[Menu]");
                }
                return this._Menu;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Menu> _Menu;
        /// <summary>
        /// There are no comments for MenuItem in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MenuItem> MenuItem
        {
            get
            {
                if ((this._MenuItem == null))
                {
                    this._MenuItem = base.CreateQuery<MenuItem>("[MenuItem]");
                }
                return this._MenuItem;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MenuItem> _MenuItem;
        /// <summary>
        /// There are no comments for Page in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Page> Page
        {
            get
            {
                if ((this._Page == null))
                {
                    this._Page = base.CreateQuery<Page>("[Page]");
                }
                return this._Page;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Page> _Page;
        /// <summary>
        /// There are no comments for PageContent in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PageContent> PageContent
        {
            get
            {
                if ((this._PageContent == null))
                {
                    this._PageContent = base.CreateQuery<PageContent>("[PageContent]");
                }
                return this._PageContent;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PageContent> _PageContent;
        /// <summary>
        /// There are no comments for Parameter in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Parameter> Parameter
        {
            get
            {
                if ((this._Parameter == null))
                {
                    this._Parameter = base.CreateQuery<Parameter>("[Parameter]");
                }
                return this._Parameter;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Parameter> _Parameter;
        /// <summary>
        /// There are no comments for ContentParameter in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ContentParameter> ContentParameter
        {
            get
            {
                if ((this._ContentParameter == null))
                {
                    this._ContentParameter = base.CreateQuery<ContentParameter>("[ContentParameter]");
                }
                return this._ContentParameter;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ContentParameter> _ContentParameter;
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        public void AddToContent(Content content)
        {
            base.AddObject("Content", content);
        }
        /// <summary>
        /// There are no comments for ContentType in the schema.
        /// </summary>
        public void AddToContentType(ContentType contentType)
        {
            base.AddObject("ContentType", contentType);
        }
        /// <summary>
        /// There are no comments for Link in the schema.
        /// </summary>
        public void AddToLink(Link link)
        {
            base.AddObject("Link", link);
        }
        /// <summary>
        /// There are no comments for LinkParameter in the schema.
        /// </summary>
        public void AddToLinkParameter(LinkParameter linkParameter)
        {
            base.AddObject("LinkParameter", linkParameter);
        }
        /// <summary>
        /// There are no comments for Master in the schema.
        /// </summary>
        public void AddToMaster(Master master)
        {
            base.AddObject("Master", master);
        }
        /// <summary>
        /// There are no comments for Menu in the schema.
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
        /// <summary>
        /// There are no comments for MenuItem in the schema.
        /// </summary>
        public void AddToMenuItem(MenuItem menuItem)
        {
            base.AddObject("MenuItem", menuItem);
        }
        /// <summary>
        /// There are no comments for Page in the schema.
        /// </summary>
        public void AddToPage(Page page)
        {
            base.AddObject("Page", page);
        }
        /// <summary>
        /// There are no comments for PageContent in the schema.
        /// </summary>
        public void AddToPageContent(PageContent pageContent)
        {
            base.AddObject("PageContent", pageContent);
        }
        /// <summary>
        /// There are no comments for Parameter in the schema.
        /// </summary>
        public void AddToParameter(Parameter parameter)
        {
            base.AddObject("Parameter", parameter);
        }
        /// <summary>
        /// There are no comments for ContentParameter in the schema.
        /// </summary>
        public void AddToContentParameter(ContentParameter contentParameter)
        {
            base.AddObject("ContentParameter", contentParameter);
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.Content in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="Content")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Content : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Content object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Content CreateContent(int id, string name)
        {
            Content content = new Content();
            content.ID = id;
            content.Name = name;
            return content;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Html in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Html
        {
            get
            {
                return this._Html;
            }
            set
            {
                this.OnHtmlChanging(value);
                this.ReportPropertyChanging("Html");
                this._Html = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Html");
                this.OnHtmlChanged();
            }
        }
        private string _Html;
        partial void OnHtmlChanging(string value);
        partial void OnHtmlChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this.ReportPropertyChanging("Url");
                this._Url = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Url");
                this.OnUrlChanged();
            }
        }
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this.ReportPropertyChanging("Image");
                this._Image = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Image");
                this.OnImageChanged();
            }
        }
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property ViewName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ViewName
        {
            get
            {
                return this._ViewName;
            }
            set
            {
                this.OnViewNameChanging(value);
                this.ReportPropertyChanging("ViewName");
                this._ViewName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ViewName");
                this.OnViewNameChanged();
            }
        }
        private string _ViewName;
        partial void OnViewNameChanging(string value);
        partial void OnViewNameChanged();
        /// <summary>
        /// There are no comments for ContentType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_Content_ContentType", "ContentType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ContentType ContentType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ContentType>("Cms.Model.FK_Content_ContentType", "ContentType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ContentType>("Cms.Model.FK_Content_ContentType", "ContentType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ContentType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ContentType> ContentTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ContentType>("Cms.Model.FK_Content_ContentType", "ContentType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ContentType>("Cms.Model.FK_Content_ContentType", "ContentType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PageContent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_PageContent_Content", "PageContent")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PageContent> PageContent
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PageContent>("Cms.Model.FK_PageContent_Content", "PageContent");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PageContent>("Cms.Model.FK_PageContent_Content", "PageContent", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ContentParameter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_ContentParameter_Content", "ContentParameter")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ContentParameter> ContentParameter
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ContentParameter>("Cms.Model.FK_ContentParameter_Content", "ContentParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ContentParameter>("Cms.Model.FK_ContentParameter_Content", "ContentParameter", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.ContentType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="ContentType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ContentType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ContentType object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static ContentType CreateContentType(int id)
        {
            ContentType contentType = new ContentType();
            contentType.ID = id;
            return contentType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_Content_ContentType", "Content")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Content> Content
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Content>("Cms.Model.FK_Content_ContentType", "Content");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Content>("Cms.Model.FK_Content_ContentType", "Content", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.Link in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="Link")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Link : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Link object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Link CreateLink(int id)
        {
            Link link = new Link();
            link.ID = id;
            return link;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this.ReportPropertyChanging("Url");
                this._Url = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Url");
                this.OnUrlChanged();
            }
        }
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property Action in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Action
        {
            get
            {
                return this._Action;
            }
            set
            {
                this.OnActionChanging(value);
                this.ReportPropertyChanging("Action");
                this._Action = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Action");
                this.OnActionChanged();
            }
        }
        private string _Action;
        partial void OnActionChanging(string value);
        partial void OnActionChanged();
        /// <summary>
        /// There are no comments for Property Controller in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Controller
        {
            get
            {
                return this._Controller;
            }
            set
            {
                this.OnControllerChanging(value);
                this.ReportPropertyChanging("Controller");
                this._Controller = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Controller");
                this.OnControllerChanged();
            }
        }
        private string _Controller;
        partial void OnControllerChanging(string value);
        partial void OnControllerChanged();
        /// <summary>
        /// There are no comments for Property Target in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Target
        {
            get
            {
                return this._Target;
            }
            set
            {
                this.OnTargetChanging(value);
                this.ReportPropertyChanging("Target");
                this._Target = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Target");
                this.OnTargetChanged();
            }
        }
        private string _Target;
        partial void OnTargetChanging(string value);
        partial void OnTargetChanged();
        /// <summary>
        /// There are no comments for Property LoginRequired in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> LoginRequired
        {
            get
            {
                return this._LoginRequired;
            }
            set
            {
                this.OnLoginRequiredChanging(value);
                this.ReportPropertyChanging("LoginRequired");
                this._LoginRequired = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LoginRequired");
                this.OnLoginRequiredChanged();
            }
        }
        private global::System.Nullable<bool> _LoginRequired;
        partial void OnLoginRequiredChanging(global::System.Nullable<bool> value);
        partial void OnLoginRequiredChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this.ReportPropertyChanging("Text");
                this._Text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Text");
                this.OnTextChanged();
            }
        }
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for Property Tooltip in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Tooltip
        {
            get
            {
                return this._Tooltip;
            }
            set
            {
                this.OnTooltipChanging(value);
                this.ReportPropertyChanging("Tooltip");
                this._Tooltip = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tooltip");
                this.OnTooltipChanged();
            }
        }
        private string _Tooltip;
        partial void OnTooltipChanging(string value);
        partial void OnTooltipChanged();
        /// <summary>
        /// There are no comments for Page in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_Link_Page", "Page")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Page Page
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Page>("Cms.Model.FK_Link_Page", "Page").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Page>("Cms.Model.FK_Link_Page", "Page").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Page in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Page> PageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Page>("Cms.Model.FK_Link_Page", "Page");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Page>("Cms.Model.FK_Link_Page", "Page", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for LinkParameter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_LinkParameter_Link", "LinkParameter")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<LinkParameter> LinkParameter
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<LinkParameter>("Cms.Model.FK_LinkParameter_Link", "LinkParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<LinkParameter>("Cms.Model.FK_LinkParameter_Link", "LinkParameter", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MenuItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_MenuItem_Link", "MenuItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<MenuItem> MenuItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<MenuItem>("Cms.Model.FK_MenuItem_Link", "MenuItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<MenuItem>("Cms.Model.FK_MenuItem_Link", "MenuItem", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.LinkParameter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="LinkParameter")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LinkParameter : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LinkParameter object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static LinkParameter CreateLinkParameter(int id)
        {
            LinkParameter linkParameter = new LinkParameter();
            linkParameter.ID = id;
            return linkParameter;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Link in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_LinkParameter_Link", "Link")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Link Link
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Link>("Cms.Model.FK_LinkParameter_Link", "Link").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Link>("Cms.Model.FK_LinkParameter_Link", "Link").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Link in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Link> LinkReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Link>("Cms.Model.FK_LinkParameter_Link", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Link>("Cms.Model.FK_LinkParameter_Link", "Link", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Parameter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_LinkParameter_Parameter", "Parameter")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Parameter Parameter
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Parameter>("Cms.Model.FK_LinkParameter_Parameter", "Parameter").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Parameter>("Cms.Model.FK_LinkParameter_Parameter", "Parameter").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Parameter in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Parameter> ParameterReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Parameter>("Cms.Model.FK_LinkParameter_Parameter", "Parameter");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Parameter>("Cms.Model.FK_LinkParameter_Parameter", "Parameter", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.Master in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="Master")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Master : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Master object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Master CreateMaster(int id, string name)
        {
            Master master = new Master();
            master.ID = id;
            master.Name = name;
            return master;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Page in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_Page_Master", "Page")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Page> Page
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Page>("Cms.Model.FK_Page_Master", "Page");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Page>("Cms.Model.FK_Page_Master", "Page", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.Menu in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="Menu")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Menu : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Menu object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="orientation">Initial value of Orientation.</param>
        public static Menu CreateMenu(int id, string name, string orientation)
        {
            Menu menu = new Menu();
            menu.ID = id;
            menu.Name = name;
            menu.Orientation = orientation;
            return menu;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Orientation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Orientation
        {
            get
            {
                return this._Orientation;
            }
            set
            {
                this.OnOrientationChanging(value);
                this.ReportPropertyChanging("Orientation");
                this._Orientation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Orientation");
                this.OnOrientationChanged();
            }
        }
        private string _Orientation;
        partial void OnOrientationChanging(string value);
        partial void OnOrientationChanged();
        /// <summary>
        /// There are no comments for MenuItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_MenuItem_Menu", "MenuItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<MenuItem> MenuItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<MenuItem>("Cms.Model.FK_MenuItem_Menu", "MenuItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<MenuItem>("Cms.Model.FK_MenuItem_Menu", "MenuItem", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.MenuItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="MenuItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MenuItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MenuItem object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="ordinal">Initial value of Ordinal.</param>
        public static MenuItem CreateMenuItem(int id, int ordinal)
        {
            MenuItem menuItem = new MenuItem();
            menuItem.ID = id;
            menuItem.Ordinal = ordinal;
            return menuItem;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Ordinal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordinal
        {
            get
            {
                return this._Ordinal;
            }
            set
            {
                this.OnOrdinalChanging(value);
                this.ReportPropertyChanging("Ordinal");
                this._Ordinal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Ordinal");
                this.OnOrdinalChanged();
            }
        }
        private int _Ordinal;
        partial void OnOrdinalChanging(int value);
        partial void OnOrdinalChanged();
        /// <summary>
        /// There are no comments for Link in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_MenuItem_Link", "Link")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Link Link
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Link>("Cms.Model.FK_MenuItem_Link", "Link").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Link>("Cms.Model.FK_MenuItem_Link", "Link").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Link in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Link> LinkReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Link>("Cms.Model.FK_MenuItem_Link", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Link>("Cms.Model.FK_MenuItem_Link", "Link", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Menu in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_MenuItem_Menu", "Menu")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Menu Menu
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Menu>("Cms.Model.FK_MenuItem_Menu", "Menu").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Menu>("Cms.Model.FK_MenuItem_Menu", "Menu").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Menu in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Menu> MenuReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Menu>("Cms.Model.FK_MenuItem_Menu", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Menu>("Cms.Model.FK_MenuItem_Menu", "Menu", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MenuItem1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_MenuItem_MenuItem", "MenuItem1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<MenuItem> MenuItem1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<MenuItem>("Cms.Model.FK_MenuItem_MenuItem", "MenuItem1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<MenuItem>("Cms.Model.FK_MenuItem_MenuItem", "MenuItem1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MenuItem2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_MenuItem_MenuItem", "MenuItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public MenuItem MenuItem2
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MenuItem>("Cms.Model.FK_MenuItem_MenuItem", "MenuItem").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MenuItem>("Cms.Model.FK_MenuItem_MenuItem", "MenuItem").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for MenuItem2 in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<MenuItem> MenuItem2Reference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<MenuItem>("Cms.Model.FK_MenuItem_MenuItem", "MenuItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<MenuItem>("Cms.Model.FK_MenuItem_MenuItem", "MenuItem", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.Page in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="Page")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Page : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Page object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="title">Initial value of Title.</param>
        public static Page CreatePage(int id, string name, string title)
        {
            Page page = new Page();
            page.ID = id;
            page.Name = name;
            page.Title = title;
            return page;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Link in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_Link_Page", "Link")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Link> Link
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Link>("Cms.Model.FK_Link_Page", "Link");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Link>("Cms.Model.FK_Link_Page", "Link", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Master in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_Page_Master", "Master")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Master Master
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Master>("Cms.Model.FK_Page_Master", "Master").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Master>("Cms.Model.FK_Page_Master", "Master").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Master in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Master> MasterReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Master>("Cms.Model.FK_Page_Master", "Master");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Master>("Cms.Model.FK_Page_Master", "Master", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PageContent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_PageContent_Page", "PageContent")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PageContent> PageContent
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PageContent>("Cms.Model.FK_PageContent_Page", "PageContent");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PageContent>("Cms.Model.FK_PageContent_Page", "PageContent", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.PageContent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="PageContent")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PageContent : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PageContent object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="placeHolder">Initial value of PlaceHolder.</param>
        /// <param name="ordinal">Initial value of Ordinal.</param>
        public static PageContent CreatePageContent(int id, string placeHolder, int ordinal)
        {
            PageContent pageContent = new PageContent();
            pageContent.ID = id;
            pageContent.PlaceHolder = placeHolder;
            pageContent.Ordinal = ordinal;
            return pageContent;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PlaceHolder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceHolder
        {
            get
            {
                return this._PlaceHolder;
            }
            set
            {
                this.OnPlaceHolderChanging(value);
                this.ReportPropertyChanging("PlaceHolder");
                this._PlaceHolder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PlaceHolder");
                this.OnPlaceHolderChanged();
            }
        }
        private string _PlaceHolder;
        partial void OnPlaceHolderChanging(string value);
        partial void OnPlaceHolderChanged();
        /// <summary>
        /// There are no comments for Property Ordinal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordinal
        {
            get
            {
                return this._Ordinal;
            }
            set
            {
                this.OnOrdinalChanging(value);
                this.ReportPropertyChanging("Ordinal");
                this._Ordinal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Ordinal");
                this.OnOrdinalChanged();
            }
        }
        private int _Ordinal;
        partial void OnOrdinalChanging(int value);
        partial void OnOrdinalChanged();
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_PageContent_Content", "Content")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Content Content
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Content>("Cms.Model.FK_PageContent_Content", "Content").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Content>("Cms.Model.FK_PageContent_Content", "Content").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Content> ContentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Content>("Cms.Model.FK_PageContent_Content", "Content");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Content>("Cms.Model.FK_PageContent_Content", "Content", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Page in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_PageContent_Page", "Page")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Page Page
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Page>("Cms.Model.FK_PageContent_Page", "Page").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Page>("Cms.Model.FK_PageContent_Page", "Page").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Page in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Page> PageReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Page>("Cms.Model.FK_PageContent_Page", "Page");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Page>("Cms.Model.FK_PageContent_Page", "Page", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.Parameter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="Parameter")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Parameter : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Parameter object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static Parameter CreateParameter(int id)
        {
            Parameter parameter = new Parameter();
            parameter.ID = id;
            return parameter;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for LinkParameter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_LinkParameter_Parameter", "LinkParameter")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<LinkParameter> LinkParameter
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<LinkParameter>("Cms.Model.FK_LinkParameter_Parameter", "LinkParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<LinkParameter>("Cms.Model.FK_LinkParameter_Parameter", "LinkParameter", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ContentParameter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_ContentParameter_Parameter", "ContentParameter")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ContentParameter> ContentParameter
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ContentParameter>("Cms.Model.FK_ContentParameter_Parameter", "ContentParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ContentParameter>("Cms.Model.FK_ContentParameter_Parameter", "ContentParameter", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Cms.Model.ContentParameter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Cms.Model", Name="ContentParameter")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ContentParameter : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ContentParameter object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static ContentParameter CreateContentParameter(int id)
        {
            ContentParameter contentParameter = new ContentParameter();
            contentParameter.ID = id;
            return contentParameter;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_ContentParameter_Content", "Content")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Content Content
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Content>("Cms.Model.FK_ContentParameter_Content", "Content").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Content>("Cms.Model.FK_ContentParameter_Content", "Content").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Content in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Content> ContentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Content>("Cms.Model.FK_ContentParameter_Content", "Content");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Content>("Cms.Model.FK_ContentParameter_Content", "Content", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Parameter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Cms.Model", "FK_ContentParameter_Parameter", "Parameter")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Parameter Parameter
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Parameter>("Cms.Model.FK_ContentParameter_Parameter", "Parameter").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Parameter>("Cms.Model.FK_ContentParameter_Parameter", "Parameter").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Parameter in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Parameter> ParameterReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Parameter>("Cms.Model.FK_ContentParameter_Parameter", "Parameter");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Parameter>("Cms.Model.FK_ContentParameter_Parameter", "Parameter", value);
                }
            }
        }
    }
}
