//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Durados.Windows.Utilities.AzureUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Folder {
            get {
                return ((string)(this["Folder"]));
            }
            set {
                this["Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Connection {
            get {
                return ((string)(this["Connection"]));
            }
            set {
                this["Connection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Query {
            get {
                return ((string)(this["Query"]));
            }
            set {
                this["Query"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureAccountName {
            get {
                return ((string)(this["AzureAccountName"]));
            }
            set {
                this["AzureAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AzureAccountKey {
            get {
                return ((string)(this["AzureAccountKey"]));
            }
            set {
                this["AzureAccountKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Hours {
            get {
                return ((int)(this["Hours"]));
            }
            set {
                this["Hours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogoFolder {
            get {
                return ((string)(this["LogoFolder"]));
            }
            set {
                this["LogoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogoConnection {
            get {
                return ((string)(this["LogoConnection"]));
            }
            set {
                this["LogoConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogoQuery {
            get {
                return ((string)(this["LogoQuery"]));
            }
            set {
                this["LogoQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogoAzureAccountName {
            get {
                return ((string)(this["LogoAzureAccountName"]));
            }
            set {
                this["LogoAzureAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogoAzureAccountKey {
            get {
                return ((string)(this["LogoAzureAccountKey"]));
            }
            set {
                this["LogoAzureAccountKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupAzureAccountName {
            get {
                return ((string)(this["BackupAzureAccountName"]));
            }
            set {
                this["BackupAzureAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupAzureAccountKey {
            get {
                return ((string)(this["BackupAzureAccountKey"]));
            }
            set {
                this["BackupAzureAccountKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupBackupAzureAccountName {
            get {
                return ((string)(this["BackupBackupAzureAccountName"]));
            }
            set {
                this["BackupBackupAzureAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupBackupAzureAccountKey {
            get {
                return ((string)(this["BackupBackupAzureAccountKey"]));
            }
            set {
                this["BackupBackupAzureAccountKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int Copies {
            get {
                return ((int)(this["Copies"]));
            }
            set {
                this["Copies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\QA\\Config\\")]
        public string ConfigPath {
            get {
                return ((string)(this["ConfigPath"]));
            }
            set {
                this["ConfigPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=backand-db-p1.cloudapp.net\\modubiz_qa,42002;Initial Catalog=ModuBiz_q" +
            "a;User ID=backqa;Password=Backqa1234!;Integrated Security=False;")]
        public string LocalConnection {
            get {
                return ((string)(this["LocalConnection"]));
            }
            set {
                this["LocalConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=backand-db-p1.cloudapp.net\\modubiz_qa,42002;Initial Catalog=ModuBiz_q" +
            "a;User ID=backqa;Password=Backqa1234!;Integrated Security=False;")]
        public string ProductionConnection {
            get {
                return ((string)(this["ProductionConnection"]));
            }
            set {
                this["ProductionConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=backand-db-p1.cloudapp.net\\modubiz_qa,42002;Initial Catalog=ModuBiz_q" +
            "a;User ID=backqa;Password=Backqa1234!;Integrated Security=False;")]
        public string QAConnection {
            get {
                return ((string)(this["QAConnection"]));
            }
            set {
                this["QAConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DuradosAppSysPrefix {
            get {
                return ((string)(this["DuradosAppSysPrefix"]));
            }
            set {
                this["DuradosAppSysPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=backand-db-p1.cloudapp.net\\modubiz_qa,42002;Initial Catalog=ModuBiz_q" +
            "a;User ID=backqa;Password=Backqa1234!;Integrated Security=False;")]
        public string DuradosMapConnectionString {
            get {
                return ((string)(this["DuradosMapConnectionString"]));
            }
            set {
                this["DuradosMapConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteFullContainerOndelete {
            get {
                return ((bool)(this["DeleteFullContainerOndelete"]));
            }
            set {
                this["DeleteFullContainerOndelete"] = value;
            }
        }
    }
}
