/*
select
'set @key = ''' + [Key] + '''
set @trans = N''' + [Translation] + '''
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)
BEGIN
	set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)
	update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang
END	
ELSE
BEGIN
	INSERT INTO Durados_TranslationKey ([key]) values (@key);
	INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)

END'
from
[dbo].[Durados_Translation] t inner join
[dbo].[Durados_TranslationKey] tk on t.TranslationKeyID = tk.ID
where  Translation<>'' 
*/

declare @key as nvarchar(250)
declare @trans as nvarchar(250)
declare @lang as int = 173
declare @keyId as int

set @key = 'More Actions'  
set @trans = N'פעולות נוספות'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END

set @key = 'Import'  
set @trans = N'יבא'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END


set @key = 'Save and '  
set @trans = N'שמור ועבור '  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END


set @key = 'Edit Mode'  
set @trans = N'מצב עריכה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END

set @key = 'Welcome '  set @trans = N'ברוכים הבאים'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Log Off'  set @trans = N'צא'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Change Password'  set @trans = N'שנה סיסמא'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Delete'  set @trans = N'מחק'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'New'  set @trans = N'חדש'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Worflow Steps'  set @trans = N'מהלך עבודה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Add'  set @trans = N'הוסף'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = '(All)'  set @trans = N'(הכל)'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Cancel'  set @trans = N'בטל'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Close'  set @trans = N'סגור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Edit'  set @trans = N'ערוך'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Maximize'  set @trans = N'הגדל'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'OK'  set @trans = N'אישור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Restore'  set @trans = N'שחזר'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Save'  set @trans = N'שמור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Save and Close'  set @trans = N'שמור וסגור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Save and Commit'  set @trans = N'שמור ובצע'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Save and Complete'  set @trans = N'שמור וסיים'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Select'  set @trans = N'בחר'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Update'  set @trans = N'עדכן'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'View'  set @trans = N'טבלה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'My Stuff'  set @trans = N'אישי'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Add Bookmark'  set @trans = N'הוסף סימנייה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Bookmarks'  set @trans = N'סימניות'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Manage Bookmarks'  set @trans = N'ניהול סימניות'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Recents'  set @trans = N'היסטוריה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Admin'  set @trans = N'מנהל'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Localization'  set @trans = N'הגדרות שפה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Hide Settings'  set @trans = N'הסתר הגדרות'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Search on text...'  set @trans = N'חפש טקסט ..'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Add new row'  set @trans = N'הוסף שורה חדשה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Duplicate'  set @trans = N'שכפל'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Select:'  set @trans = N'בחר:'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'All'  set @trans = N'הכל'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Clear'  set @trans = N'נקה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'History'  set @trans = N'היסטוריה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Excel:'  set @trans = N'גליון:'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Export'  set @trans = N'יצא'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Print current page'  set @trans = N'הדפס דף נוכחי'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Print'  set @trans = N'הדפס'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Send a link to the selected row'  set @trans = N'שלח קישור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Send'  set @trans = N'שלח'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Filter:'  set @trans = N'סינון:'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Apply'  set @trans = N'החל'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Refresh the view content'  set @trans = N'סנן'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Refresh'  set @trans = N'רענן'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Search'  set @trans = N'חפש'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Page'  set @trans = N'עמוד'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'out of'  set @trans = N'מתוך'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Page Size:'  set @trans = N'גודל עמוד:'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Total Rows:'  set @trans = N'סה"כ שורות:'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Hide'  set @trans = N'הסתר'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Unhide'  set @trans = N'הצג'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Left'  set @trans = N'ימינה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Right'  set @trans = N'שמאלה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Before'  set @trans = N'לפני'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'After'  set @trans = N'אחרי'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Rename'  set @trans = N'שנה שם'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Config'  set @trans = N'עצב'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Properties'  set @trans = N'מאפיינים'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Commit'  set @trans = N'בצע'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Are you sure that you want to delete the selected rows?'  set @trans = N'האם אתה/י בטוח שאתה רוצה למחוק שורה זו?'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = '(Empty)'  set @trans = N'(ריק)'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Translation'  set @trans = N'תירגום'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Comments'  set @trans = N'הערות'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Diagnose'  set @trans = N'אבחן'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Dictionary'  set @trans = N'מילון'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Edit Mode:'  set @trans = N'מצב עריכה:'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Copy'  set @trans = N'העתק'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Paste'  set @trans = N'הדבק'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Login was unsuccessful. Please correct the errors and try again.'  set @trans = N'כניסה שגויה. נא תקו את השגיאות הבאות ונסה שנית.'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Username'  set @trans = N'שם משתמש'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Password'  set @trans = N'סיסמא'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Remember me'  set @trans = N'זכור אותי'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Log On'  set @trans = N'כנס'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'You must specify a password.'  set @trans = N'נא הכנס סיסמא'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'The username or password provided is incorrect.'  set @trans = N'שם משתמש או סיסמא שגויים'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Key'  set @trans = N'מפתח'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Up'  set @trans = N'למעלה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Down'  set @trans = N'למטה'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Insert'  set @trans = N'הכנס'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Clone'  set @trans = N'שכפל'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Sync'  set @trans = N'סנכרן'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Source'  set @trans = N'מקור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Destination'  set @trans = N'יעד'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Base'  set @trans = N'מקור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Cloned'  set @trans = N'שיכפול'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Open'  set @trans = N'פתח'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Reorder'  set @trans = N'סדר מחדש'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Please enter your username and password'  set @trans = N'אנא הכנס שם משתמש וסיסמא'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Browser Go Back'  set @trans = N'חזור לטבלה הקודמת'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Back'  set @trans = N'חזור'  if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END

set @key = 'Show'  
set @trans = N'הצג'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END

set @key = 'Show:'  
set @trans = N'הצג:'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END

set @key = 'Show Settings'  
set @trans = N'הצג הגדרות'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Set As Default'  
set @trans = N'שמור כברירת מחדל'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Restore Default'  
set @trans = N'שחזר ברירת מחדל'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Add Column'  
set @trans = N'הוסף עמודה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Messages'  
set @trans = N'הודעות'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END

set @key = 'Action'  
set @trans = N'פעולה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Name'  
set @trans = N'שם'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Date'  
set @trans = N'תאריך'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Field'  
set @trans = N'שדה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Old'  
set @trans = N'קודם'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'User'  
set @trans = N'משתמש'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'History Log'  
set @trans = N'נתוני היסטוריה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Of'  
set @trans = N'מתןך'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'New View'  
set @trans = N'הוסף טבלה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Add Views'  
set @trans = N'הוסף טבלאות'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Help'  
set @trans = N'עזרה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Welcome to'  
set @trans = N'ברוך הבא'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Move:'  
set @trans = N'הזז:'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'More Actions'  
set @trans = N'פעולות נוספות'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Public'  
set @trans = N'כללי'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Admin'  
set @trans = N'מנהל מערכת'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'My Apps'  
set @trans = N'אפליקציות'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'My Charts'  
set @trans = N'דוחות'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'My Inbox'  
set @trans = N'דואר נכנס'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Tree Filter'  
set @trans = N'עץ פילטור'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Filter:'  
set @trans = N'פילטור:'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Sort By:'  
set @trans = N'מיין באמצעות:'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Greater Than'  
set @trans = N'גדול מ'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Greater Than Or Equal To'  
set @trans = N'גדול מ או שווה ל'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Less Than'  
set @trans = N'קטן מ'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Less Than Or Equal To'  
set @trans = N'קטן מ או שווה ל'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Equals'  
set @trans = N'שווה'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Does Not Equal'  
set @trans = N'שונה מ'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Between'  
set @trans = N'בין'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Begins With'  
set @trans = N'מתחיל ב'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Ends With'  
set @trans = N'מסתיים ב'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Contains'  
set @trans = N'מכיל'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Does Not Contain'  
set @trans = N'לא מכיל'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'To'  
set @trans = N'ל'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Is Blank'  
set @trans = N'ריק'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
set @key = 'Is Not Blank'  
set @trans = N'לא ריק'  
if exists(select [key] from [Durados_TranslationKey] where [key] = @key)  BEGIN   set @keyId = (select [ID] from [dbo].[Durados_TranslationKey] where [key] = @key)   update [dbo].[Durados_Translation] set [Translation] = @trans where [TranslationKeyID]=@keyId and [LanguageID]=@lang  END   ELSE  BEGIN   INSERT INTO Durados_TranslationKey ([key]) values (@key);   INSERT INTO Durados_Translation ([TranslationKeyID], [LanguageID], [Translation]) values (@@IDENTITY, @lang, @trans)    END
